# Menangani Error dan Exception

  Saat membuat program, seorang pemrogram tidak akan terlepas dari kondisi-kondisi yang terkait dengan program yang dia buat, khususnya kemungkinan terjadinya kesalahan. Python mempunyai berbagai macam konstruksi untuk mendeteksi error (yang paling sederhana, misalnya SyntaxError) jika terdapat hal-hal yang bisa diketahui kesalahannya sejak awal. Meski demikian, sering kali jika tidak ada error juga tidak menjamin bahwa saat dijalankan tidak akan terjadi hal-hal yang di luar dugaan. Tugas pemrogram adalah mengantisipasi berbagai macam kondisi tersebut.

  Saat terjadi error, pemrogram melihat pada error yang terjadi, setelah itu memperbaiki berdasarkan error yang muncul. Seringkali hal ini juga melibatkan pembacaan manual / dokumentasi dan penggunaan sumber daya di Internet (StackOverflow dan lain-lain) untuk melihat kemungkinan solusi. Berikut ini adalah contoh perintah-perintah yang menimbulkan error (kata yang dicetak tebal tambahan dari penulis untuk menjelaskan nilai error):

```python
>>> f = open('abc.txt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'abc.txt'
>>> f = open('abca.txt','f')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid mode: 'f'
>>> print 'abcdefg'
  File "<stdin>", line 1
    print 'abcdefg'
                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('abcdefg')?
```

  Setiap terjadi error, Python akan memunculkan exception atau suatu kondisi “pengecualian”. Pemrogram biasanya harus waspada terhadap berbagai kemungkinan error serta exception yang terjadi untuk diantisipasi. Untuk mengantisipasi exception, gunakan blok try … except … else … finally.

```python 
# except.py
 
import sys
 
# tanpa exception handling
# b = float(input('masukkan angka float: '))
# amasukkan angka float: f
# Traceback (most recent call last):
#  File "except.py", line 5, in <module>
#    b = float(input('masukkan angka float: '))
# ValueError: could not convert string to float: 'f'
 
# Setelah dihandle:
try:
    a = float(input("masukkan angka float: "))
except ValueError:
    print('harus memasukkan nilai float')
 
# Jika tidak tau kemungkinan error:
try:
    a = float(input("masukkan angka: "))
    b = float(input("masukkan angka pembagi: "))
    z = a/b
except:
    print("Error:", sys.exc_info()[0])
else:
    print('Hasil bagi: ', z)
finally:
    # bagian ini biasanya untuk clean-up, di dunia nyata 
    # biasanya berisi bagian utk close connection, menutup
    # file dan lain-lain
    print('Selesai')
# hasil:
# masukkan angka: 40
# masukkan angka pembagi: 0
# Error: <class 'ZeroDivisionError'>
```
